api/urls.py
from django.urls import path

from api.views import StatusView, RelayDetail, RelayToggle

app_name = 'api'

urlpatterns = [
    path('', StatusView.as_view(), name='status'),
    path('relay/<int:pk>/', RelayDetail.as_view(), name='relay-detail'),
    path('relay/<int:pk>/toggle/', RelayToggle.as_view(), name='relay-toggle'),
]

relays/urls.py
from django.urls import path

from relays.views import RelayListView, RelayDetailView, RelayUpdateView, RelayDeleteView, AuditLogView, \
    RelayCreateView, CreateRelayShareView, RevokeRelayShareView, RelayShareUpdateView, RelayChangeStateView, \
    ChannelListView, ChannelUpdateView, ChannelDeleteView, ChannelTestView, ChannelCreateView, WizardView, test_relay_channel

app_name = 'relays'

urlpatterns = [
    path('setup/', WizardView.as_view(), name='setup-wizard'),

    path('', RelayListView.as_view(), name='relay-list'),
    path('create/', RelayCreateView.as_view(), name='relay-create'),
    path('<int:pk>/', RelayDetailView.as_view(), name='relay-detail'),
    path('<int:pk>/update/', RelayUpdateView.as_view(), name='relay-update'),
    path('<int:pk>/delete/', RelayDeleteView.as_view(), name='relay-delete'),
    path('<int:pk>/toggle/', RelayChangeStateView.as_view(), name='relay-toggle'),

    # Channels
    path('channels/', ChannelListView.as_view(), name='channel-list'),
    path('channels/create/', ChannelCreateView.as_view(), name='channel-create'),
    path('channels/<int:pk>/update/', ChannelUpdateView.as_view(), name='channel-update'),
    path('channels/<int:pk>/delete/', ChannelDeleteView.as_view(), name='channel-delete'),
    path('channels/<int:pk>/test/', ChannelTestView.as_view(), name='channel-test'),
    path('internal/testchannel/', test_relay_channel, name='test-channel'),

    # Audit Log
    path('auditlog/', AuditLogView.as_view(), name='audit-log'),

    # Shares
    path('<int:pk>/share/', CreateRelayShareView.as_view(), name='share-relay'),
    path('shares/<int:pk>/revoke/', RevokeRelayShareView.as_view(), name='revoke-share'),
    path('shares/<int:pk>/bump/', RelayShareUpdateView.as_view(), name='bump-share-permissions')
]

smart_relays/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from smart_relays.utils.config import get_project_config


def redirect_to_default_page(request):
    return redirect(get_project_config().default_page, permanent=True)


urlpatterns = [
    path('', redirect_to_default_page),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('relays/', include('relays.urls')),
    path('admin/', admin.site.urls),
]

relays/forms.py
from django import forms

from accounts.models import User
from relays.models import Relay, UserRelayShare, Channel
from smart_relays.utils.config import get_project_config


class RelayUpdateForm(forms.ModelForm):
    class Meta:
        model = Relay
        fields = '__all__'
        labels = {
            'user': ''
        }
        widgets = {
            'user': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'textarea'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False

    def clean(self):
        try:
            if self.instance.user != self.cleaned_data['user']:
                raise forms.ValidationError('You cannot change the owner of a relay.')
        except KeyError:
            return super().clean()


class RelayCreateForm(forms.ModelForm):
    class Meta:
        model = Relay
        fields = '__all__'
        labels = {
            'user': ''
        }
        widgets = {
            'user': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'input'}),
        }
        help_texts = {
            'name': 'The name of the relay',
            'description': 'A description of the relay',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['channel'].queryset = Channel.objects.unused()


class ShareRelayForm(forms.ModelForm):
    class Meta:
        model = UserRelayShare
        fields = '__all__'
        widgets = {
            'relay': forms.HiddenInput(),
        }

    def __init__(self, possible_recipients: tuple[User] = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = possible_recipients if possible_recipients is not None else User.objects.all()
        self.fields['permission_level'].choices = UserRelayShare.PermissionLevel.choices


class ChannelForm(forms.ModelForm):
    class Meta:
        model = Channel
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'pin': forms.NumberInput(attrs={'class': 'input'}),
        }
        help_texts = {
            'name': 'The name of the relay',
            'pin': 'The GPIO pin number (BCM)',
        }

relays/views.py
import json

from django.contrib import messages
from django.contrib.auth import login
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView, TemplateView

from accounts.forms import UserCreateForm
from accounts.utils.access.user_relay_access_tests import owner_or_shared, owner_or_full_access, \
    owner_or_at_least_control, superuser, owner_or_full_access_or_superuser, owner_or_shared_or_superuser
from relays.forms import RelayUpdateForm, RelayCreateForm, ShareRelayForm, ChannelForm
from relays.models import Relay, RelayStateChange, RelayCreateRecord, RelayUpdateRecord, UserRelayShare, \
    RelayShareRecord, Channel
from smart_relays.models import ApplicationData
from smart_relays.utils.config import get_relays_config, get_project_config
from smart_relays.utils.template import push_form_errors_to_messages
from smart_relays.views import SmartRelaysView


class WizardView(SmartRelaysView, TemplateView):
    template_name = 'wizard.html'
    title = 'Setup Wizard'
    login_required = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['wizard_data'] = ApplicationData.objects.get(key='setup_wizard').data

        return context

    def get(self, request, *args, **kwargs):
        if ApplicationData.objects.get(key='setup_wizard').data['completed']:
            return HttpResponseRedirect(get_project_config().default_page)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        wizard_data = ApplicationData.objects.get(key='setup_wizard')
        current_step = int(request.POST.get('step'))
        match current_step:
            case 0:
                return self.__step_0_handler(request, wizard_data)
            case 1:
                return self.__step_1_handler(request, wizard_data)
            case 2:
                return self.__setp_2_handler(request, wizard_data)
        return HttpResponseRedirect(request.path)

    def __step_0_handler(self, request: HttpRequest, wizard_data: ApplicationData):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            admin = form.save()

            admin.is_superuser = True
            admin.is_staff = True
            admin.save()

            login(request, admin)

            wizard_data.data['step'] = 1
            wizard_data.save()
        else:
            push_form_errors_to_messages(request, form)
        return HttpResponseRedirect(request.path)

    def __step_1_handler(self, request: HttpRequest, wizard_data: ApplicationData):
        for pin in [pin for pin in list(json.loads(str(request.POST['pins']))) if pin]:
            Channel.objects.create(pin=pin)
        wizard_data.data['step'] = 2
        wizard_data.save()
        return HttpResponseRedirect(request.path)

    def __setp_2_handler(self, request: HttpRequest, wizard_data: ApplicationData):
        wizard_data.data = {'completed': True}
        wizard_data.save()
        return HttpResponseRedirect(request.path)


def test_relay_channel(request: HttpRequest):
    pin = int(request.GET.get('pin') or 0)
    from relays.tasks import test_pin
    test_pin.delay(pin)
    return HttpResponse()


# ----------------------------------------
# Relay Views
# ----------------------------------------

class RelayListView(SmartRelaysView, ListView):
    template_name = 'relay_list.html'
    title = 'Relays'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = RelayCreateForm(initial={'user': self.request.user})
        return context

    def get_queryset(self):
        return Relay.objects.for_user(self.request.user)


class RelayDetailView(SmartRelaysView, DetailView):
    model = Relay
    template_name = 'relay_detail.html'

    def test_func(self, request: HttpRequest):
        return owner_or_shared_or_superuser(self.request.user, self.get_object())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['state_history'] = {
            str(state_change.timestamp): state_change.new_state for state_change in
            RelayStateChange.objects.for_relay(self.get_object())
        }

        context['share_form'] = ShareRelayForm(
            self.get_object().get_possible_recipients(),
            initial={'relay': self.get_object()}
        )
        context['relay_shares'] = UserRelayShare.objects.for_relay(self.get_object())

        default_audit_log_limit = get_relays_config().audit_log_pagination_page_size
        audit_log_limit = int(self.request.GET.get('audit_log_limit', default_audit_log_limit))
        context['audit_log_limit'] = audit_log_limit, default_audit_log_limit
        context['audit_log'] = self.get_object().get_audit_log(audit_log_limit)

        context['permissions'] = {
            'sharing': owner_or_full_access_or_superuser(self.request.user, self.get_object()),
            'audit_log': owner_or_full_access_or_superuser(self.request.user, self.get_object()),
        }

        context['quick_scheduling'] = [
            ('5 min', 5 * 60, 'is-info'),
            ('15 min', 15 * 60, 'is-info'),
            ('30 min', 30 * 60, 'is-info'),
            ('1 hour', 60 * 60, 'is-link'),
            ('6 hours', 6 * 60 * 60, 'is-link'),
            ('12 hours', 12 * 60 * 60, 'is-link'),
            ('Tomorrow (this time)', 24 * 60 * 60, 'is-primary'),
        ]

        return context

    def get_title(self):
        return self.object.name


class RelayUpdateView(SmartRelaysView, UpdateView):
    model = Relay
    form_class = RelayUpdateForm
    template_name = 'relay_form.html'
    title = 'Relay update'

    def test_func(self, request: HttpRequest):
        return owner_or_full_access_or_superuser(self.request.user, self.get_object())

    def get_page_subtitle(self):
        return self.object

    def post(self, request, *args, **kwargs):
        # Put this request into a queue so that the save handler can have access to it
        Relay.update_requests.put(request)
        return super().post(request, *args, **kwargs)


class RelayCreateView(SmartRelaysView, CreateView):
    http_method_names = ['post']
    model = Relay
    form_class = RelayCreateForm
    success_url = reverse_lazy('relays:relay-list')

    def form_invalid(self, form):
        push_form_errors_to_messages(self.request, form)
        return redirect(self.success_url)

    def post(self, request, *args, **kwargs):
        # Put this request into a queue so that the save handler can have access to it
        Relay.update_requests.put(request)
        return super().post(request, *args, **kwargs)


class RelayDeleteView(SmartRelaysView, DeleteView):
    http_method_names = ('post',)
    model = Relay
    success_url = reverse_lazy('relays:relay-list')

    def test_func(self, request: HttpRequest):
        return owner_or_full_access_or_superuser(self.request.user, self.get_object())


class RelayChangeStateView(SmartRelaysView, View):
    relay: Relay = None

    def handle_test_fail(self, request) -> HttpResponse:
        return HttpResponseForbidden()

    def test_func(self, request: HttpRequest):
        self.relay = Relay.objects.get(pk=request.resolver_match.kwargs['pk'])
        return owner_or_at_least_control(request.user, self.relay)

    def post(self, request, *args, **kwargs):
        try:
            delay = int(request.POST['delay'])
            messages.success(request, f'Relay {self.relay.name} scheduled to be toggled in {delay/60} minutes.')
        except KeyError:
            delay = 0
            messages.success(request, f'Relay {self.relay.name} toggled.')
        self.relay.toggle(request, delay)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


# ----------------------------------------
# Channel Views
# ----------------------------------------
class ChannelListView(SmartRelaysView, ListView):
    template_name = 'channel_list.html'
    title = 'Channels'
    model = Channel

    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['create_form'] = ChannelForm()

        return context


class ChannelUpdateView(SmartRelaysView, UpdateView):
    model = Channel
    form_class = ChannelForm
    template_name = 'channel_form.html'
    title = 'Channel update'
    success_url = reverse_lazy('relays:channel-list')

    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def get_page_subtitle(self):
        return self.object


class ChannelCreateView(SmartRelaysView, CreateView):
    http_method_names = ('post',)
    model = Channel
    form_class = ChannelForm
    success_url = reverse_lazy('relays:channel-list')

    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def form_invalid(self, form):
        push_form_errors_to_messages(self.request, form)
        return redirect(self.success_url)


class ChannelDeleteView(SmartRelaysView, DeleteView):
    http_method_names = ('post',)
    model = Channel
    success_url = reverse_lazy('relays:channel-list')

    def test_func(self, request: HttpRequest):
        return superuser(self.request.user)


class ChannelTestView(SmartRelaysView, View):
    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def get(self, request, *args, **kwargs):
        from relays.tasks import test_channel
        channel: Channel = Channel.objects.get(pk=kwargs['pk'])

        test_channel.delay(channel.pk)

relays/templates/audit_log.html
{% extends 'base_template.html' %}
{% block body_content %}
    <div class="columns is-multiline">
        <div class="column is-12">
            {% include 'includes/audit_log_table.html' with rows=page_obj paginator=paginator %}
        </div>
        {% comment %}
        RESERVED FOR LIKE A FILTER MENU OR <SMTH></SMTH>
        <div class="column">

        </div>{% endcomment %}
    </div>
{% endblock %}

relays/templates/channel_form.html
{% extends 'base_template.html' %}
{% load common_template %}
{% block body_content %}
    <div class="columns">
        <div class="column is-full is-6-desktop">
            <form method="post">{% csrf_token %}
                {% render_form form %}
                <div class="field is-grouped">
                    <div class="control">
                        <input type="submit" class="button is-link" value="Save"/>
                    </div>
                    <div class="control">
                        <a href="{% url 'relays:channel-list' %}" class="button is-link is-light">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

relays/templates/channel_list.html
{% extends 'base_template.html' %}
{% block body_content %}
    <div class="columns is-multiline">
        <div class="column is-12">
            {% include 'includes/channel_table.html' with rows=object_list %}
        </div>
        {% include 'includes/create_modal_button.html' with label='Add channel' data_target='create-channel-modal' %}
    </div>
{% endblock %}
{% block modals %}
    {% for channel in object_list %}
        {% include 'modals/delete_channel_modal.html' with channel=channel %}
    {% endfor %}

    {% include 'modals/create_channel_modal.html' %}
{% endblock %}

relays/templates/relay_detail.html
{% extends 'base_template.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/relay_details.css' %}">
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/pagination.js' %}" defer></script>
    {{ state_history|json_script:'state_history' }}
{% endblock %}
{% block page_subtitle %}
    State:
    {% if object.get_current_state.new_state %}
        <span class="tag is-success">ON</span>
    {% else %}
        <span class="tag is-danger">OFF</span>
    {% endif %}
{% endblock %}
{% block body_content %}
    <p class="is-size-4 mb-3">Overview</p>
    <div class="columns">
        <div class="column">
            <p class="has-text-weight-bold">Description</p>
            <p>{{ object.description }}</p>
        </div>
    </div>

    <p class="is-size-4 mb-3">Scheduling</p>
    <div class="columns">
        <div class="column">
            <label class="label">Quick scheduling <span
                    class="has-text-weight-light">(toggle the relay after)</span></label>
            <div class="buttons">
                {% for button in quick_scheduling %}
                    <form action="{% url 'relays:relay-toggle' object.pk %}" method="post" class="mr-2">
                        {% csrf_token %}
                        <input type="hidden" name="delay" value="{{ button.1 }}">
                        <button class="button is-light {{ button.2 }}">{{ button.0 }}</button>
                    </form>
                {% endfor %}
            </div>
        </div>
    </div>



    <div>
        <p class="is-size-4 mb-3">State history</p>
        <canvas id="history"></canvas>
        <script src="{% static 'js/relay_detail.js' %}"></script>
    </div>

    {% if permissions.sharing %}
        <div id="sharing" class="is-flex is-align-items-center mt-5 mb-2">
            <p class="is-size-4">Sharing</p>
            <div class="is-hidden-mobile ml-3">
                {% include 'includes/share_relay_form.html' with form=share_form %}
            </div>
        </div>
        <div class="is-hidden-tablet mb-2">
            {% include 'includes/share_relay_form.html' with form=share_form %}
        </div>
        {% include 'includes/relay_shares_table.html' with shares=relay_shares %}
    {% endif %}

    {% if permissions.audit_log %}
        <p class="is-size-4 mt-5">Audit log</p>
        {% include 'includes/audit_log_table__without_relays.html' with rows=audit_log limit=audit_log_limit.0 base_limit=audit_log_limit.1 limit_query_parameter='audit_log_limit' limit_button_id='limit-button' %}
    {% endif %}
{% endblock %}

relays/templates/relay_form.html
{% extends 'base_template.html' %}
{% load common_template %}
{% block body_content %}
    <div class="columns">
        <div class="column is-full is-6-desktop">
            <form method="post">{% csrf_token %}
                {% render_form form %}
                <div class="field is-grouped">
                    <div class="control">
                        <input type="submit" class="button is-link" value="Save"/>
                    </div>
                    <div class="control">
                        <a href="{% url 'relays:relay-list' %}" class="button is-link is-light">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

relays/templates/relay_list.html
{% extends 'base_template.html' %}
{% load relays_template %}
{% load static %}
{% block extra_js %}
    <script src="{% static 'js/relay_control.js' %}" defer></script>
    <script id="csrf_token" type="application/json">{{ csrf_token }}</script>
{% endblock %}
{% block status %}
    {% slot_status %}
{% endblock %}
{% block body_content %}
    <div class="columns is-multiline">
        {% if not object_list %}
            <div class="column">
                <span class="has-text-grey-light">No relay has been created yet, start by creating one first</span>
            </div>
        {% endif %}
        {% for relay in object_list %}
            <div class="column is-full-mobile is-6-tablet is-6-desktop is-4-widescreen is-3-fullhd">
                {% render_relay_card relay %}
            </div>
        {% endfor %}
        {% include 'includes/create_modal_button.html' with label='Add relay' data_target='create-relay-modal' %}
    </div>
{% endblock %}
{% block modals %}
    {% for relay in object_list %}
        {% include 'modals/delete_relay_modal.html' with relay_id=relay.pk relay_name=relay.name %}
    {% endfor %}

    {% include 'modals/create_relay_modal.html' %}
{% endblock %}

relays/templates/wizard.html
{% extends 'base_template.html' %}
{% load static %}
{% block extra_css %}
    <link href="{% static 'css/bulma-steps.min.css' %}" rel="stylesheet">
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/setup_wizard.js' %}" defer></script>
    {{ wizard_data|json_script:"wizard_data" }}
{% endblock %}
{% block navigation %}{% endblock %}
{% block header %}{% endblock %}
{% block body %}
    <div class="container mt-5">
        <div class="steps">
            <div class="step-item">
                <div class="step-marker">1</div>
                <div class="step-details">
                    <p class="step-title">Account</p>
                </div>
            </div>
            <div class="step-item">
                <div class="step-marker">2</div>
                <div class="step-details">
                    <p class="step-title">GPIO</p>
                </div>
            </div>
            <div class="step-item">
                <div class="step-marker">3</div>
                <div class="step-details">
                    <p class="step-title">Finish</p>
                </div>
            </div>
            <div class="steps-content">
                <div class="columns">
                    <div class="column is-3"></div>
                    <div class="column is-6">
                        <div class="mb-5">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="notification {{ message.tags }}">
                                        <button class="delete" onclick="this.parentElement.remove()"></button>
                                        {{ message|safe }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="step-content has-text-centered is-active">
                            <form id="wizard-form" method="post" onsubmit="return onSubmit()">
                                {% csrf_token %}
                                <input class="wizard-step-input" type="hidden" name="step">
                                {% if wizard_data.step == 0 %}
                                    {% include 'includes/wizard/create_admin.html' %}
                                {% elif wizard_data.step == 1 %}
                                    {% include 'includes/wizard/gpio.html' %}
                                {% elif wizard_data.step == 2 %}
                                    {% include 'includes/wizard/finish.html' %}
                                {% endif %}
                            </form>
                        </div>
                    </div>
                    <div class="column is-3"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}