api/urls.py
from django.urls import path

from api.views import StatusView, RelayDetail, RelayToggle

app_name = 'api'

urlpatterns = [
    path('', StatusView.as_view(), name='status'),
    path('relay/<int:pk>/', RelayDetail.as_view(), name='relay-detail'),
    path('relay/<int:pk>/toggle/', RelayToggle.as_view(), name='relay-toggle'),
]

relays/urls.py
from django.urls import path

from relays.views import RelayListView, RelayDetailView, RelayUpdateView, RelayDeleteView, AuditLogView, \
    RelayCreateView, CreateRelayShareView, RevokeRelayShareView, RelayShareUpdateView, RelayChangeStateView, \
    ChannelListView, ChannelUpdateView, ChannelDeleteView, ChannelTestView, ChannelCreateView, WizardView, test_relay_channel

app_name = 'relays'

urlpatterns = [
    path('setup/', WizardView.as_view(), name='setup-wizard'),

    path('', RelayListView.as_view(), name='relay-list'),
    path('create/', RelayCreateView.as_view(), name='relay-create'),
    path('<int:pk>/', RelayDetailView.as_view(), name='relay-detail'),
    path('<int:pk>/update/', RelayUpdateView.as_view(), name='relay-update'),
    path('<int:pk>/delete/', RelayDeleteView.as_view(), name='relay-delete'),
    path('<int:pk>/toggle/', RelayChangeStateView.as_view(), name='relay-toggle'),

    # Channels
    path('channels/', ChannelListView.as_view(), name='channel-list'),
    path('channels/create/', ChannelCreateView.as_view(), name='channel-create'),
    path('channels/<int:pk>/update/', ChannelUpdateView.as_view(), name='channel-update'),
    path('channels/<int:pk>/delete/', ChannelDeleteView.as_view(), name='channel-delete'),
    path('channels/<int:pk>/test/', ChannelTestView.as_view(), name='channel-test'),
    path('internal/testchannel/', test_relay_channel, name='test-channel'),

    # Audit Log
    path('auditlog/', AuditLogView.as_view(), name='audit-log'),

    # Shares
    path('<int:pk>/share/', CreateRelayShareView.as_view(), name='share-relay'),
    path('shares/<int:pk>/revoke/', RevokeRelayShareView.as_view(), name='revoke-share'),
    path('shares/<int:pk>/bump/', RelayShareUpdateView.as_view(), name='bump-share-permissions')
]

smart_relays/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from smart_relays.utils.config import get_project_config


def redirect_to_default_page(request):
    return redirect(get_project_config().default_page, permanent=True)


urlpatterns = [
    path('', redirect_to_default_page),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('relays/', include('relays.urls')),
    path('admin/', admin.site.urls),
]

relays/forms.py
from django import forms

from accounts.models import User
from relays.models import Relay, UserRelayShare, Channel
from smart_relays.utils.config import get_project_config


class RelayUpdateForm(forms.ModelForm):
    class Meta:
        model = Relay
        fields = '__all__'
        labels = {
            'user': ''
        }
        widgets = {
            'user': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'textarea'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False

    def clean(self):
        try:
            if self.instance.user != self.cleaned_data['user']:
                raise forms.ValidationError('You cannot change the owner of a relay.')
        except KeyError:
            return super().clean()


class RelayCreateForm(forms.ModelForm):
    class Meta:
        model = Relay
        fields = '__all__'
        labels = {
            'user': ''
        }
        widgets = {
            'user': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'input'}),
        }
        help_texts = {
            'name': 'The name of the relay',
            'description': 'A description of the relay',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['channel'].queryset = Channel.objects.unused()


class ShareRelayForm(forms.ModelForm):
    class Meta:
        model = UserRelayShare
        fields = '__all__'
        widgets = {
            'relay': forms.HiddenInput(),
        }

    def __init__(self, possible_recipients: tuple[User] = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = possible_recipients if possible_recipients is not None else User.objects.all()
        self.fields['permission_level'].choices = UserRelayShare.PermissionLevel.choices


class ChannelForm(forms.ModelForm):
    class Meta:
        model = Channel
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'pin': forms.NumberInput(attrs={'class': 'input'}),
        }
        help_texts = {
            'name': 'The name of the relay',
            'pin': 'The GPIO pin number (BCM)',
        }

relays/views.py
import json

from django.contrib import messages
from django.contrib.auth import login
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView, TemplateView

from accounts.forms import UserCreateForm
from accounts.utils.access.user_relay_access_tests import owner_or_shared, owner_or_full_access, \
    owner_or_at_least_control, superuser, owner_or_full_access_or_superuser, owner_or_shared_or_superuser
from relays.forms import RelayUpdateForm, RelayCreateForm, ShareRelayForm, ChannelForm
from relays.models import Relay, RelayStateChange, RelayCreateRecord, RelayUpdateRecord, UserRelayShare, \
    RelayShareRecord, Channel
from smart_relays.models import ApplicationData
from smart_relays.utils.config import get_relays_config, get_project_config
from smart_relays.utils.template import push_form_errors_to_messages
from smart_relays.views import SmartRelaysView


class WizardView(SmartRelaysView, TemplateView):
    template_name = 'wizard.html'
    title = 'Setup Wizard'
    login_required = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['wizard_data'] = ApplicationData.objects.get(key='setup_wizard').data

        return context

    def get(self, request, *args, **kwargs):
        if ApplicationData.objects.get(key='setup_wizard').data['completed']:
            return HttpResponseRedirect(get_project_config().default_page)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        wizard_data = ApplicationData.objects.get(key='setup_wizard')
        current_step = int(request.POST.get('step'))
        match current_step:
            case 0:
                return self.__step_0_handler(request, wizard_data)
            case 1:
                return self.__step_1_handler(request, wizard_data)
            case 2:
                return self.__setp_2_handler(request, wizard_data)
        return HttpResponseRedirect(request.path)

    def __step_0_handler(self, request: HttpRequest, wizard_data: ApplicationData):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            admin = form.save()

            admin.is_superuser = True
            admin.is_staff = True
            admin.save()

            login(request, admin)

            wizard_data.data['step'] = 1
            wizard_data.save()
        else:
            push_form_errors_to_messages(request, form)
        return HttpResponseRedirect(request.path)

    def __step_1_handler(self, request: HttpRequest, wizard_data: ApplicationData):
        for pin in [pin for pin in list(json.loads(str(request.POST['pins']))) if pin]:
            Channel.objects.create(pin=pin)
        wizard_data.data['step'] = 2
        wizard_data.save()
        return HttpResponseRedirect(request.path)

    def __setp_2_handler(self, request: HttpRequest, wizard_data: ApplicationData):
        wizard_data.data = {'completed': True}
        wizard_data.save()
        return HttpResponseRedirect(request.path)


def test_relay_channel(request: HttpRequest):
    pin = int(request.GET.get('pin') or 0)
    from relays.tasks import test_pin
    test_pin.delay(pin)
    return HttpResponse()


# ----------------------------------------
# Relay Views
# ----------------------------------------

class RelayListView(SmartRelaysView, ListView):
    template_name = 'relay_list.html'
    title = 'Relays'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = RelayCreateForm(initial={'user': self.request.user})
        return context

    def get_queryset(self):
        return Relay.objects.for_user(self.request.user)


class RelayDetailView(SmartRelaysView, DetailView):
    model = Relay
    template_name = 'relay_detail.html'

    def test_func(self, request: HttpRequest):
        return owner_or_shared_or_superuser(self.request.user, self.get_object())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['state_history'] = {
            str(state_change.timestamp): state_change.new_state for state_change in
            RelayStateChange.objects.for_relay(self.get_object())
        }

        context['share_form'] = ShareRelayForm(
            self.get_object().get_possible_recipients(),
            initial={'relay': self.get_object()}
        )
        context['relay_shares'] = UserRelayShare.objects.for_relay(self.get_object())

        default_audit_log_limit = get_relays_config().audit_log_pagination_page_size
        audit_log_limit = int(self.request.GET.get('audit_log_limit', default_audit_log_limit))
        context['audit_log_limit'] = audit_log_limit, default_audit_log_limit
        context['audit_log'] = self.get_object().get_audit_log(audit_log_limit)

        context['permissions'] = {
            'sharing': owner_or_full_access_or_superuser(self.request.user, self.get_object()),
            'audit_log': owner_or_full_access_or_superuser(self.request.user, self.get_object()),
        }

        context['quick_scheduling'] = [
            ('5 min', 5 * 60, 'is-info'),
            ('15 min', 15 * 60, 'is-info'),
            ('30 min', 30 * 60, 'is-info'),
            ('1 hour', 60 * 60, 'is-link'),
            ('6 hours', 6 * 60 * 60, 'is-link'),
            ('12 hours', 12 * 60 * 60, 'is-link'),
            ('Tomorrow (this time)', 24 * 60 * 60, 'is-primary'),
        ]

        return context

    def get_title(self):
        return self.object.name


class RelayUpdateView(SmartRelaysView, UpdateView):
    model = Relay
    form_class = RelayUpdateForm
    template_name = 'relay_form.html'
    title = 'Relay update'

    def test_func(self, request: HttpRequest):
        return owner_or_full_access_or_superuser(self.request.user, self.get_object())

    def get_page_subtitle(self):
        return self.object

    def post(self, request, *args, **kwargs):
        # Put this request into a queue so that the save handler can have access to it
        Relay.update_requests.put(request)
        return super().post(request, *args, **kwargs)


class RelayCreateView(SmartRelaysView, CreateView):
    http_method_names = ['post']
    model = Relay
    form_class = RelayCreateForm
    success_url = reverse_lazy('relays:relay-list')

    def form_invalid(self, form):
        push_form_errors_to_messages(self.request, form)
        return redirect(self.success_url)

    def post(self, request, *args, **kwargs):
        # Put this request into a queue so that the save handler can have access to it
        Relay.update_requests.put(request)
        return super().post(request, *args, **kwargs)


class RelayDeleteView(SmartRelaysView, DeleteView):
    http_method_names = ('post',)
    model = Relay
    success_url = reverse_lazy('relays:relay-list')

    def test_func(self, request: HttpRequest):
        return owner_or_full_access_or_superuser(self.request.user, self.get_object())


class RelayChangeStateView(SmartRelaysView, View):
    relay: Relay = None

    def handle_test_fail(self, request) -> HttpResponse:
        return HttpResponseForbidden()

    def test_func(self, request: HttpRequest):
        self.relay = Relay.objects.get(pk=request.resolver_match.kwargs['pk'])
        return owner_or_at_least_control(request.user, self.relay)

    def post(self, request, *args, **kwargs):
        try:
            delay = int(request.POST['delay'])
            messages.success(request, f'Relay {self.relay.name} scheduled to be toggled in {delay/60} minutes.')
        except KeyError:
            delay = 0
            messages.success(request, f'Relay {self.relay.name} toggled.')
        self.relay.toggle(request, delay)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


# ----------------------------------------
# Channel Views
# ----------------------------------------
class ChannelListView(SmartRelaysView, ListView):
    template_name = 'channel_list.html'
    title = 'Channels'
    model = Channel

    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['create_form'] = ChannelForm()

        return context


class ChannelUpdateView(SmartRelaysView, UpdateView):
    model = Channel
    form_class = ChannelForm
    template_name = 'channel_form.html'
    title = 'Channel update'
    success_url = reverse_lazy('relays:channel-list')

    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def get_page_subtitle(self):
        return self.object


class ChannelCreateView(SmartRelaysView, CreateView):
    http_method_names = ('post',)
    model = Channel
    form_class = ChannelForm
    success_url = reverse_lazy('relays:channel-list')

    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def form_invalid(self, form):
        push_form_errors_to_messages(self.request, form)
        return redirect(self.success_url)


class ChannelDeleteView(SmartRelaysView, DeleteView):
    http_method_names = ('post',)
    model = Channel
    success_url = reverse_lazy('relays:channel-list')

    def test_func(self, request: HttpRequest):
        return superuser(self.request.user)


class ChannelTestView(SmartRelaysView, View):
    def test_func(self, request: HttpRequest):
        return superuser(request.user)

    def get(self, request, *args, **kwargs):
        from relays.tasks import test_channel
        channel: Channel = Channel.objects.get(pk=kwargs['pk'])

        test_channel.delay(channel.pk)

relays/templates/includes/audit_log_table.html
{% extends 'includes/base_table.html' %}
{% load relays_template %}
{% block head %}
    <th>Date</th>
    <th>Relay</th>
    <th>User</th>
    <th>Action</th>
{% endblock %}
{% block for_each_row %}
    {% render_audit_log row True %}
{% endblock %}
{% block empty_message %}
    No activity has been recorded so far
{% endblock %}

relays/templates/includes/audit_log_table__without_relays.html
{% extends 'includes/audit_log_table.html' %}
{% load relays_template %}
{% block head %}
    <th>Date</th>
    <th>User</th>
    <th>Action</th>
{% endblock %}
{% block for_each_row %}
    {% render_audit_log row %}
{% endblock %}

relays/templates/includes/audit_log_table_global.html
{% load render %}
{% if logs %}
    <table class="table is-fullwidth is-hoverable">
        <thead>
        <tr>
            <th>Date</th>
            <th>Relay</th>
            <th>User</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for record in logs %}
            {% render_audit_log record True %}
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <span class="has-text-grey-light">No activity has been recorded so far</span>
{% endif %}

relays/templates/includes/channel_table.html
{% extends 'includes/base_table.html' %}
{% load relays_template %}
{% block head %}
    <th>Name</th>
    <th>GPIO Pin <span class="has-text-weight-normal">(BCM)</span></th>
    <th>In use</th>
    <th style="text-align: center">Actions</th>
{% endblock %}
{% block for_each_row %}
    <tr>
        <td>{{ row.name }}</td>
        <td>{{ row.pin }}</td>
        <td>
            {% if row.is_in_use %}
                <i class="fa-solid fa-check has-text-success"></i>
                <span class="has-text-grey">({{ row.relay }})</span>
            {% else %}
                <i class="fa-solid fa-x has-text-danger"></i>
            {% endif %}
        </td>
        <td class="is-flex is-justify-content-center">
            <a href="{% url 'relays:channel-test' row.pk %}" title="Test this channel">
                <span class="icon">
                    <i class="fa-solid fa-circle-check has-text-success"></i>
                </span>
            </a>
            <a href="{% url 'relays:channel-update' row.pk %}">
                <span class="icon">
                    <i class="fa-solid fa-pencil has-text-info"></i>
                </span>
            </a>
            <a class="modal-button" data-target="delete-channel-modal-{{ row.pk }}">
                <span class="icon">
                    <i class="fa-solid fa-trash has-text-danger"></i>
                </span>
            </a>
        </td>
    </tr>
{% endblock %}
{% block empty_message %}
    No relay channels have been added yet.
{% endblock %}

relays/templates/includes/relay_card.html
{% load common_template %}
<div class="card">
    <header
            style="height:65px"
            id="relayCardHeader{{ relay.pk }}"
            class="relay-card-header card-header {% if relay.get_current_state.new_state %}has-background-success-light{% else %}has-background-danger-light{% endif %}"
    >
        {% if share %}
            <div class="card-header-title is-flex-direction-column is-align-items-start">
                <p class="m-0">{{ relay.name }}</p>
                <p class="is-size-7 has-text-weight-normal">shared by <span
                        class="has-text-weight-bold">{{ share.grantor }}</span></p>
            </div>
        {% else %}
            <p class="card-header-title">
                {{ relay.name }}
            </p>
        {% endif %}
        <button class="card-header-icon" aria-label="more options">
            <span class="mr-3 is-size-4"></span>
            <input
                    id="relaySwitch{{ relay.pk }}"
                    type="checkbox"
                    class="switch is-rounded {% if relay.get_current_state.new_state %}is-success{% endif %} is-loading"
                    onclick="toggleRelay(this, {{ relay.pk }})"
                    {% if relay.get_current_state.new_state %}checked{% endif %}
                    {% if share.is_read_only %}disabled{% endif %}
            >
            <label for="relaySwitch{{ relay.pk }}"></label>
        </button>
    </header>
    <div class="card-content">
        <div class="content">
            <p>
                {% if relay.description %}
                    {{ relay.description }}
                {% else %}
                    <span class="has-text-grey-light">No description</span>
                {% endif %}
            </p>
            <p class="m-0">
                <b>Created:</b> {{ relay.created_at }}
            </p>
            <p class="m-0">
                <b>Last state change:</b>
                <span id="relayHistory_{{ relay.pk }}">
                    {% if relay.get_current_state %}
                        {{ relay.get_current_state.timestamp|time_delta_nice }}
                    {% else %}
                        <span class="has-text-grey-light">No history</span>
                    {% endif %}
                </span>
            </p>
        </div>
    </div>
    <footer class="card-footer">
        <a href="{% url 'relays:relay-detail' relay.pk %}" class="card-footer-item">
           <span class="icon">
                <i class="fa-solid fa-circle-info"></i>
           </span>
            Detail
        </a>
        {% if not share or share.is_full_access %}
            <a href="{% url 'relays:relay-update' relay.pk %}" class="card-footer-item has-text-info">
                <span class="icon">
                    <i class="fa-solid fa-pen-to-square"></i>
                </span>
                Edit
            </a>
            <a class="card-footer-item has-text-danger modal-button" data-target="delete-relay-modal-{{ relay.pk }}">
                <span class="icon">
                    <i class="fa-solid fa-trash"></i>
                </span>
                Delete
            </a>
        {% endif %}
    </footer>
</div>

relays/templates/includes/relay_shares_table.html
{% load relays_template %}
{% if shares %}
    <table class="table is-fullwidth is-hoverable">
        <thead>
        <tr>
            <th class="is-hidden-touch">Sharing started on</th>
            <th>User</th>
            <th>
                <span class="is-hidden-mobile">Permission level</span>
                <span class="is-hidden-tablet">Permissions</span>
            </th>
            <th style="text-align: center">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for share in shares %}
            <tr>
                <td class="is-hidden-touch">{{ share.created_at }}</td>
                <td>
                    <span class="is-hidden-touch">{{ share.user.get_verbose_name }}</span>
                    <span class="is-hidden-desktop">{{ share.user.username }}</span>
                </td>
                <td style="vertical-align: middle">
                    {% render_permission_level_progress_bar share %}
                </td>
                <td id="relay-shares-action-items" class="is-flex is-justify-content-center">
                    {% if share.permission_level < share.highest_permission_level %}
                        <form action="{% url 'relays:bump-share-permissions' share.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="permission_level" value="{{ share.permission_level|add:1 }}">
                            <button type="submit" class="button is-small is-success" title="Increase permission level">
                                <span class="icon">
                                    <i class="fas fa-arrow-up"></i>
                                </span>
                            </button>
                        </form>
                    {% endif %}
                    {% if share.permission_level > share.lowest_permission_level %}
                        <form action="{% url 'relays:bump-share-permissions' share.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="permission_level" value="{{ share.permission_level|add:-1 }}">
                            <button type="submit" class="button is-small is-warning" title="Decrease permission level">
                                <span class="icon">
                                    <i class="fas fa-arrow-down"></i>
                                </span>
                            </button>
                        </form>
                    {% endif %}
                    <form action="{% url 'relays:revoke-share' share.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="button is-small is-danger is-hidden-tablet">
                            <span class="icon">
                                <i class="fas fa-trash"></i>
                            </span>
                        </button>
                        <button type="submit" class="button is-small is-danger is-hidden-mobile">
                            <span class="icon">
                                <i class="fas fa-trash"></i>
                            </span>
                            <span>Revoke share</span>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <span class="has-text-grey-light">You are not sharing this relay with anyone</span>
{% endif %}

relays/templates/includes/share_relay_form.html
<form method="post" action="{% url 'relays:share-relay' object.pk %}">
    {% csrf_token %}
    {{ form.relay }}
    <div class="field has-addons">
        <div class="control">
            <div class="select">
                {{ form.user }}
            </div>
        </div>
        <div class="control">
            <div class="select">
                {{ form.permission_level }}
            </div>
        </div>
        <div class="control">
            <button type="submit" class="button is-success">
                    <span class="icon mr-1">
                        <i class="fa-solid fa-check"></i>
                    </span>
                <span>Grant share</span>
            </button>
        </div>
    </div>
</form>

relays/templates/includes/slot_status.html
{% if slots_max == 0 %}
    <p class="has-text-grey-light">No slots available</p>
{% else %}
    <p class="has-text-grey-light">
        {{ slots_used }}/{{ slots_max }} slots used (<b>{% if slots_left <= 0 %}Full{% else %}{{ slots_left }}
        remaining{% endif %}</b>)
    </p>
{% endif %}
<progress class="progress {{ progress_color }}" value="{{ slots_used }}" max="{{ slots_max }}"></progress>